In [1]:
import pandas as pd
import numpy as np
import keras
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow
from PIL import Image
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D

%matplotlib inline

In [2]:
dataset_train = pd.read_csv('../Sign-Language-to-Text-Conversion/Dataset/sign_mnist_train.csv')
dataset_train.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,3,107,118,127,134,139,143,146,150,153,...,207,207,207,207,206,206,206,204,203,202
1,6,155,157,156,156,156,157,156,158,158,...,69,149,128,87,94,163,175,103,135,149
2,2,187,188,188,187,187,186,187,188,187,...,202,201,200,199,198,199,198,195,194,195
3,2,211,211,212,212,211,210,211,210,210,...,235,234,233,231,230,226,225,222,229,163
4,13,164,167,170,172,176,179,180,184,185,...,92,105,105,108,133,163,157,163,164,179

In [3]:
dataset_test = pd.read_csv('../Sign-Language-to-Text-Conversion/Dataset/sign_mnist_test.csv')
dataset_test.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,6.0,149.0,149.0,150.0,150.0,150.0,151.0,151.0,150.0,151.0,...,138.0,148.0,127.0,89.0,82.0,96.0,106.0,112.0,120.0,107.0
1,5.0,126.0,128.0,131.0,132.0,133.0,134.0,135.0,135.0,136.0,...,47.0,104.0,194.0,183.0,186.0,184.0,184.0,184.0,182.0,180.0
2,10.0,85.0,88.0,92.0,96.0,105.0,123.0,135.0,143.0,147.0,...,68.0,166.0,242.0,227.0,230.0,227.0,226.0,225.0,224.0,222.0
3,0.0,203.0,205.0,207.0,206.0,207.0,209.0,210.0,209.0,210.0,...,154.0,248.0,247.0,248.0,253.0,236.0,230.0,240.0,253.0,255.0
4,3.0,188.0,191.0,193.0,195.0,199.0,201.0,202.0,203.0,203.0,...,26.0,40.0,64.0,48.0,29.0,46.0,49.0,46.0,46.0,53.0

In [4]:
print('Number of images in the training set: {}'.format(dataset_train.shape[0]))
print('Number of images in the test set: {}'.format(dataset_test.shape[0]))
d = int((dataset_train.shape[1] - 1)**0.5)
print('Shape of the images: {} x {}'.format(d,d))

Number of images in the training set: 27455
Number of images in the test set: 14605
Shape of the images: 28 x 28

In [5]:
labels = dataset_train['label']
labels_test = dataset_test['label']

In [6]:
dataset_train.drop('label', axis = 1, inplace = True)
print(dataset_train.shape)
dataset_test.drop('label', axis = 1, inplace = True)
print(dataset_test.shape)

(27455, 784)
(14605, 784)

In [7]:
x_train = dataset_train.values.reshape(dataset_train.shape[0],28,28,1)
x_test = dataset_test.values.reshape(dataset_test.shape[0],28,28,1)

In [8]:
x_train = x_train / 255.0
x_test = x_test / 255.0
print(x_train.shape)
print(x_test.shape)

(27455, 28, 28, 1)
(14605, 28, 28, 1)

In [9]:
#plt.imshow(x_train[100].reshape(28,28), cmap='gray')

In [10]:
labels = to_categorical(labels)
y_train=labels
print(labels.shape)
labels_test = to_categorical(labels_test)
y_test=labels_test
print(labels_test.shape)

(27455, 25)

IndexError: index -2147483648 is out of bounds for axis 1 with size 25

In [ ]:
batch_size = 128
num_classes = 10
epochs = 12

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(28,28,1)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

In [ ]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=tf.keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])